pipeline {
    agent any
    tools { 
        maven 'M3' 
    }
    stages {
        stage('Initialize') {
            steps {
                echo 'Checking Java and Maven versions...'
                sh 'mvn -version'
                sh 'java -version'
            }
        }
        stage('Build') {
            steps {
                echo 'Building the application...'
                sh 'mvn clean package'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying application...'
                sh 'echo "Simulating deployment..."'
                sh 'java -cp target/jenkins-demo-app-1.0-SNAPSHOT.jar com.example.SimpleApp'
            }
        }
    }
}
